### ISSUE TITLE
获取TopViewController逻辑应该有问题

### ISSUE THREAD

**Issue by wufeifan890330** [Liya86/LYUIExposureManager#1]
`
- (UIViewController *)topViewController:(UIViewController *)rootViewController {
    if ([rootViewController isKindOfClass:[UINavigationController class]]) {
        UINavigationController *navigationController = (UINavigationController *)rootViewController;
        return [self topViewController:[navigationController.viewControllers lastObject]];
    }
    if ([rootViewController isKindOfClass:[UITabBarController class]]) {
        UITabBarController *tabController = (UITabBarController *)rootViewController;
        return [self topViewController:tabController.selectedViewController];
    }
    if (rootViewController.presentedViewController) {
        return [self topViewController:rootViewController];
    }
    return rootViewController;
}`

如果rootViewController.presentedViewController != nil，递归退不出。

此处应该是

`
if (rootViewController.presentedViewController) {
        return [self topViewController:rootViewController.presentedViewController];
    }
`

未测试，扒拉代码看到的。如有问题请指正~

**Comment by Liya86** [comment]
🐸～ 你说的对，已改嘞 (o^^o)
